# permissions for end users to edit edgeloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgeloadbalancer-editor-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - edgeloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - edgeloadbalancers/status
  verbs:
  - get
