---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - edgeloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - edgeloadbalancers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.openyurt.io
  resources:
  - edgeloadbalancers/status
  verbs:
  - get
  - patch
  - update
