// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: protocol/protocol.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConWireClient is the client API for ConWire service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConWireClient interface {
	Push(ctx context.Context, in *Usecase, opts ...grpc.CallOption) (*Usecase, error)
}

type conWireClient struct {
	cc grpc.ClientConnInterface
}

func NewConWireClient(cc grpc.ClientConnInterface) ConWireClient {
	return &conWireClient{cc}
}

func (c *conWireClient) Push(ctx context.Context, in *Usecase, opts ...grpc.CallOption) (*Usecase, error) {
	out := new(Usecase)
	err := c.cc.Invoke(ctx, "/ConWire/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConWireServer is the server API for ConWire service.
// All implementations must embed UnimplementedConWireServer
// for forward compatibility
type ConWireServer interface {
	Push(context.Context, *Usecase) (*Usecase, error)
	mustEmbedUnimplementedConWireServer()
}

// UnimplementedConWireServer must be embedded to have forward compatible implementations.
type UnimplementedConWireServer struct {
}

func (UnimplementedConWireServer) Push(context.Context, *Usecase) (*Usecase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedConWireServer) mustEmbedUnimplementedConWireServer() {}

// UnsafeConWireServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConWireServer will
// result in compilation errors.
type UnsafeConWireServer interface {
	mustEmbedUnimplementedConWireServer()
}

func RegisterConWireServer(s grpc.ServiceRegistrar, srv ConWireServer) {
	s.RegisterService(&ConWire_ServiceDesc, srv)
}

func _ConWire_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Usecase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConWireServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ConWire/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConWireServer).Push(ctx, req.(*Usecase))
	}
	return interceptor(ctx, in, info, handler)
}

// ConWire_ServiceDesc is the grpc.ServiceDesc for ConWire service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConWire_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ConWire",
	HandlerType: (*ConWireServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _ConWire_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/protocol.proto",
}
